.TH ELFBSP 6 "September 2022"
.SH NAME
elfbsp \- a nodes builder for modern DOOM source ports
.SH SYNOPSIS
.B elfbsp
[\fI\,OPTION\/\fR]... \fI\,FILE\/\fR...
.SH DESCRIPTION
.B ELFBSP
is a simple nodes builder for modern DOOM source ports.
It can build standard DOOM nodes and Extended ZDoom format nodes.
Multiple wad files can be processed, and each file is modified in-place.
There is an option to backup files before processing them.
.SH OPTIONS
Short options begin with a single dash, followed by one
or more letters, where each letter is a distinct option
(i.e. short options can be mixed together).
Long options begin with two dashes, followed by a whole word.
When an option needs a value, it should be placed in the next
argument.
.PP
Filenames and options may be freely mixed, and the order of
options on the command line is not significant.
All files are processed with the same settings.
.PP
The special option '\-\-' causes all following arguments to be
interpreted as filenames.  This allows specifying a file which
begins with a hyphen.
.TP
.B \-v \-\-verbose
Produces more verbose output to the terminal.
Some warnings which are normally hidden (except
for a final tally) will be shown when enabled.
.TP
.B \-vv \-\-very\-verbose
Equivalent to using \-\-verbose twice, and causes lots of
wonderfully useless information about each level to be displayed.
.TP
.B \-vvv \-\-super\-verbose
Equivalent to using \-\-verbose three times, and enables the
display of all the minor issues (such as unclosed subsectors).
.TP
.B \-b \-\-backup
Backs up each input file before processing it.
The backup files will have the ".bak" extension
(replacing the ".wad" extension).  If the backup
file already exists, it will be silently overwritten.
.TP
.B \-m \-\-map NAME(s)
Specifies one or more maps to process.
All other maps will be skipped (not touched at all).
The same set of maps applies to every given wad file.
The default behavior is to process every map in the wad.

Map names must be the lump name, like "MAP01" or "E2M3",
and cannot be abbreviated.  A range of maps can be
specified using a hyphen, such as "MAP04-MAP07".
Several map names and/or ranges can be given, using
commas to separate them, such as "MAP01,MAP03,MAP05".

NOTE: spaces cannot be used to separate map names.
.TP
.B \-t \-\-type ##
Forces a specific Node format version. Choices include:
 \- 0 => plain Doom format nodes
 \- 1 => DeepBSPv4
 \- 2 => XNOD
 \- 3 => XGLN
 \- 4 => XGL2
 \- 5 => XGL3

ELFBSP will automatically choose the minimum format needed when certain
limits are reached, raising from Doom to XNOD and XGL3, as is needed.
DeepBSPv4, XGLN and XGL2 are considered deprecated and are only made
available for source port testing purposes.
.TP
.B \-c \-\-cost ##
Sets the cost for making seg splits.
The value is a number between 1 and 32.
Larger values try to reduce the number of seg splits,
whereas smaller values produce more balanced BSP trees.
The default value is 11.
.TP
.B \-o \-\-output FILE
This option is provided *only* for compatibility with
existing node builders.  It causes the input file to be
copied to the specified file, and that file is the one
processed.  This option cannot be used with multiple
input files, or with the \-\-backup option.
.TP
.B \-h \-\-help
Displays a brief help screen, then exits.
.TP
.B \-\-version
Displays a version string, then exits.
.SH EXIT STATUS
.TP
0
if OK.
.TP
1
if nothing was built (no matching maps).
.TP
2
if one or more maps failed to build properly.
.TP
3
if a fatal error occurred.
.SH COPYRIGHT
ELFBSP is Copyright \(co 2025 Guilherme Miranda, Andrew Apted,
Colin Reed, and Lee Killough, et al.
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.PP
This program is is distributed in the hope that it
will be useful, but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
.SH "SEE ALSO"
.PP
The ELFBSP home page: https://github.com/elf-alchemist/elfbsp
